### ISSUE TITLE
Deconvolution step for ConSep Data

### ISSUE THREAD

**Issue by Ajaz-Ahmad** [Mr-TalhaIlyas/TSFD-Net-for-Nuclei-Segmentation-and-Classification#11]
Hi Talha

Thanks for updating evaluation and post-processing steps. Can you also mention for deconvolution of stain for Consep data. I tried using the default h_e_r values but does not seems to do a fair job. The maximum iou for boundary detection is 0.4 therefore, the boundaries do not form well and the performance is low.
Can you suggest something on improving the result?
I am training on consep dataset (1000,1000) . The data is prepared with step size of 256 with overlap for the last window to keep the patch consistent. 
Thanks in advance

**Comment by Mr-TalhaIlyas** [comment]
Those values can't be assumed. As for the boundaries you could try increasing contrast and saturation of images.
