### ISSUE TITLE
slide-level inference script

### ISSUE THREAD

**Issue by kaczmarj** [Mr-TalhaIlyas/TSFD-Net-for-Nuclei-Segmentation-and-Classification#12]
Hi, I saw the TSFD paper and was very excited to try it out. Will you release a slide-level inference script? Similar to what hovernet has.

**Comment by Mr-TalhaIlyas** [comment]
Hi, thanks for support I have added the inference level script. [here](https://github.com/Mr-TalhaIlyas/TSFD/tree/master/slide_inference)
