### ISSUE TITLE
Cannot reproduce performance as per paper

### ISSUE THREAD

**Issue by Mgryn** [Mr-TalhaIlyas/TSFD-Net-for-Nuclei-Segmentation-and-Classification#13]
@Mr-TalhaIlyas 
Hi, I wanted to reproduce the results obtained in the paper on Pannuke dataset, but I don't seem to get anywhere near. 
I tried running the script as it is in the current version of the repository, but I could not get it to start, so I reverted to original loss combination as per paper:
```python
def SEG_Loss(y_true, y_pred):
    # weight fot tp hr v3 only
    loss = FocalTverskyLoss(y_true, y_pred, smooth=1e-7) + [0.4 * Weighted_BCEnDice_loss(y_true, y_pred)]
    
    return tf.math.reduce_mean(loss)
  
def INST_Loss(y_true, y_pred):
    # weight fot tp hr v3 only
    loss = FocalTverskyLoss(y_true, y_pred, smooth=1e-7) + [0.4 * Combo_loss(y_true, y_pred, smooth=1e-7)]

    return tf.math.reduce_mean(loss)
```
Which worked and I could train the model.
I have used the splits provided in `TSFD/tsfd_weights/splits` but after finishing the training the results were bad:
![image](https://user-images.githubusercontent.com/55716616/219286317-cf0513ab-4b65-472e-a089-b973d018eb24.png)

I used provided weights (`Efficent_pet_203_clf-end.h5`) for testing and the results are much better:
![image](https://user-images.githubusercontent.com/55716616/219286456-cd7242cc-f4e1-40ee-9e28-52849619f990.png)

I would like to ask what parameters and loss combination did you use to train `Efficent_pet_203_clf-end.h5` model:
- what was the dropout value ? I did couple of runs and in my case dropout > 0.1 negatively affects model performance. Did you use init_dropout = 0.2 ?
- what loss combination was used ? 
- there seems to be a problem with running the script with loss configuration as it is currently in the repository:
    - Focal_loss function does not have `smooth` parameter
    - after removing the parameter, I am getting an error regarding BCE calculation: `TypeError: Input 'y' of 'Mul' Op has type float16 that does not match type uint8 of argument 'x'.`
    - when casting x to float, there is an issue with dimensions: `tensorflow.python.framework.errors_impl.InvalidArgumentError:  required broadcastable shapes
         [[node SEG_Loss/mul (defined at home/mateusz/org_TSFD/scripts/losses.py:27) ]] [Op:__inference_test_function_64607]`

I would appreciate it if you could help me solve the issue and be able to train the model so it achieves similar results to  `Efficent_pet_203_clf-end.h5`. Thank you very much in advance.

**Comment by MukulKadaskar** [comment]
> @Mr-TalhaIlyas Hi, I wanted to reproduce the results obtained in the paper on Pannuke dataset, but I don't seem to get anywhere near. I tried running the script as it is in the current version of the repository, but I could not get it to start, so I reverted to original loss combination as per paper:
> 
> ```python
> def SEG_Loss(y_true, y_pred):
>     # weight fot tp hr v3 only
>     loss = FocalTverskyLoss(y_true, y_pred, smooth=1e-7) + [0.4 * Weighted_BCEnDice_loss(y_true, y_pred)]
>     
>     return tf.math.reduce_mean(loss)
>   
> def INST_Loss(y_true, y_pred):
>     # weight fot tp hr v3 only
>     loss = FocalTverskyLoss(y_true, y_pred, smooth=1e-7) + [0.4 * Combo_loss(y_true, y_pred, smooth=1e-7)]
> 
>     return tf.math.reduce_mean(loss)
> ```
> 
> Which worked and I could train the model. I have used the splits provided in `TSFD/tsfd_weights/splits` but after finishing the training the results were bad: ![image](https://user-images.githubusercontent.com/55716616/219286317-cf0513ab-4b65-472e-a089-b973d018eb24.png)
> 
> I used provided weights (`Efficent_pet_203_clf-end.h5`) for testing and the results are much better: ![image](https://user-images.githubusercontent.com/55716616/219286456-cd7242cc-f4e1-40ee-9e28-52849619f990.png)
> 
> I would like to ask what parameters and loss combination did you use to train `Efficent_pet_203_clf-end.h5` model:
> 
>     * what was the dropout value ? I did couple of runs and in my case dropout > 0.1 negatively affects model performance. Did you use init_dropout = 0.2 ?
> 
>     * what loss combination was used ?
> 
>     * there seems to be a problem with running the script with loss configuration as it is currently in the repository:
>       
>       * Focal_loss function does not have `smooth` parameter
>       * after removing the parameter, I am getting an error regarding BCE calculation: `TypeError: Input 'y' of 'Mul' Op has type float16 that does not match type uint8 of argument 'x'.`
>       * when casting x to float, there is an issue with dimensions: `tensorflow.python.framework.errors_impl.InvalidArgumentError:  required broadcastable shapes [[node SEG_Loss/mul (defined at home/mateusz/org_TSFD/scripts/losses.py:27) ]] [Op:__inference_test_function_64607]`
> 
> 
> I would appreciate it if you could help me solve the issue and be able to train the model so it achieves similar results to `Efficent_pet_203_clf-end.h5`. Thank you very much in advance.

This will really help!

**Comment by MukulKadaskar** [comment]
The results in pre-trained models do not match the results as reported in the paper.

**Comment by Mr-TalhaIlyas** [comment]
Those results look completely ridiculous, I think there is a problem in the data preparation step. I flipped the first and last channels of the 1-hot encoded labels so that background is at 0th channels, i.e., flipped the 0 and 5 pixel values [here](https://github.com/Mr-TalhaIlyas/Prerpcessing-PanNuke-Nuclei-Instance-Segmentation-Dataset/blob/master/scripts/process_pannuke.py#L58). From the confusion matrix that seems to be the case.

**Comment by Mgryn** [comment]
@Mr-TalhaIlyas 
Sorry, I missed your comment. 
I did not modify your scripts for data processing, the confusion matrix was plotted while ignoring the background channel (0). 
I did modify the augmentation to include noise and intensity transforms as in the paper and initial commit to the repository.
Unfortunately my results are still not as reported in the paper and also much lower than the ones I get when using `Efficent_pet_203_clf-end.h5` model:
![image](https://user-images.githubusercontent.com/55716616/233385423-7285859c-b73b-407f-adbf-5b3d24a79493.png)
![image](https://user-images.githubusercontent.com/55716616/233385364-f7500184-5c69-44fd-9513-777f18bbe499.png)

The issue is not solved.
I would appreciate your help in obtaining similar performance to the one in the paper, or `Efficent_pet_203_clf-end.h5` model.
Could you please answer the questions I posted ? 
> - what was the dropout value ? I did couple of runs and in my case dropout > 0.1 negatively affects model performance. Did you use init_dropout = 0.2 ?
> - what loss combination was used ?

Are you able to run the code as it is in it's current form in the repository without issues ?
