### ISSUE TITLE
Callbacks not provided 

### ISSUE THREAD

**Issue by lucas-sancere** [Mr-TalhaIlyas/TSFD-Net-for-Nuclei-Segmentation-and-Classification#2]
Dear Mr-TalhaIlyas, thank you for your work and the amazing paper.

  I saw you deleted your callbacks scripts for several github repo, as this one. Is it possible to have the script in order to run the code? I don't understand why it is not here anymore, maybe I am missing something.
  
  As there is: 
  `from callbacks import [...]`
  In [main_tsfd.py](https://github.com/Mr-TalhaIlyas/TSFD/blob/master/scripts/main_tsfd.py) 
  I tried in vain to install `callbacks` library in case the functions were part of the library and not from the missing script, but then I reached:
  ```bash
   Traceback (most recent call last):
  File "main_tsfd.py", line 23, in <module>
    from callbacks import PlotLearning, PredictionCallback, CustomLearningRateScheduler, CustomDropoutScheduler
ImportError: cannot import name 'PlotLearning'
  ```
  
Thank you for your help and support, 
Lucas

**Comment by Mr-TalhaIlyas** [comment]
Hi Lucas,
Thanks for reaching out. Actually at that time I wrote my own learning rate scheduler script as `callbacks` but later on `tensorflow` provided a built-in class for that schedule [here](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/schedules/CosineDecay). So I thought it would be better to use the one provided by the `tf` so i removed the `callbacks`.  But I have updated the repo again and added the custom callback script again. If you need to more schedulers or losses  you can check [here](https://github.com/Mr-TalhaIlyas/Learning-Rate-Schedulers-Packege-Tensorflow-PyTorch-Keras) and [here](https://github.com/Mr-TalhaIlyas/Loss-Functions-Package-Tensorflow-Keras-PyTorch) .

**Comment by lucas-sancere** [comment]
Hi Mr-TalhaIlyas, 

 Thank you for your help and the update! Fast and comprehensive.
  I will check it out.
