### ISSUE TITLE
Layers and some Custom Callbacks not provided

### ISSUE THREAD

**Issue by lucas-sancere** [Mr-TalhaIlyas/TSFD-Net-for-Nuclei-Segmentation-and-Classification#4]
Dear Mr-TalhaIlyas, thank you for your work.

I just came back to this repo, and now I see that the `layers.py` script is missing and was deleted before. Exactly same issue as before with the `callbacks.py` script.

Is it possible to have it back?  

And also some Callbacks are still missing `PlotLearning`, `PredictionCallback`, `CustomLearningRateScheduler`, `CustomDropoutScheduler`, `CustomKernelRegularizer` and I would like to have it instead of re-doing it myself, knowing that this code is  open source as stated in the paper. 

Thank you for the paper, your help and support, 
Lucas

**Comment by Mr-TalhaIlyas** [comment]
hi,
i fixed all the broken imports have a look, now it should work fine.
