### ISSUE TITLE
Handling consep data as image size is 540x540

### ISSUE THREAD

**Issue by Ajaz-Ahmad** [Mr-TalhaIlyas/TSFD-Net-for-Nuclei-Segmentation-and-Classification#7]
Hi Mr Talhallyas

Thanks for sharing your work, can you please provide details on how did you handled Consep Dataset or any other dataset if the patch/tile size is not a factor 256. For example, consep has tile size of 540x540x3

Thanks in advance

**Comment by Mr-TalhaIlyas** [comment]
Hi there, 
sorry for late reply. for training you could either resize or just crop the data and for testing you could use a patching algorithm to run inference on full images (extract/split then merge). an example of patching library is [pip EMPatches](https://pypi.org/project/empatches/)
