### ISSUE TITLE
Weights file provided does not perform as per the paper

### ISSUE THREAD

**Issue by Ajaz-Ahmad** [Mr-TalhaIlyas/TSFD-Net-for-Nuclei-Segmentation-and-Classification#8]
Hi Mr Talhallyas,

I used the weights provided Efficient_pet_203_clf-end. But the result I get is far away from the information in the paper. Can you please provide weight file

| Metric            |   Value |
|-------------------|---------|
| loss              |  0.6111 |
| clf_out_loss      |  0.0016 |
| seg_out_loss      |  0.2662 |
| inst_out_loss     |  0.3402 |
| clf_out_accuracy  |  0.9308 |
| seg_out_mean_iou  |  0.7642 |
| inst_out_mean_iou |  0.4022

Nuclei Type    |     PQ |
|----------------|--------|
| Neoplastic     | 0.2069 |
| Inflammatory   | 0.2909 |
| Connective     | 0.1036 |
| Dead           | 0.5984 |
| Non-Neoplastic | 0.5625 |

**Comment by Mr-TalhaIlyas** [comment]
Hi,
I checked the weights they are working fine. Maybe  you are using a different split to test the model/weights, have a look at updated description [here](https://github.com/Mr-TalhaIlyas/TSFD/tree/master/tsfd_weights).
